<!Doctype html>
<html lang="es">
	<head>
		<title>menu</title>
		  <meta charset="UTF-8">
		  <meta name="viewport" content="width-device-width, user-scalable=no, initial-scale=1, maximun-scale=1, minimun-scale=1">
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" href="{{ base_url()}}/css/estilos.css">
		<link rel="stylesheet" href="{{ base_url()}}/fonts/style.css">
	</head>
	<body>
    <header>
			<input type="checkbox" id="btn-menu">
			<label for="btn-menu"><img src="{{ base_url()}}/img/menu.png" alt=""></label>
				<nav class="menu">
					<ul>
					  <li class="menuactividad"><a href="#">Actividad</a>
							<ul>
                 <li><a href="login.">Crear</a>
								 <li><a href="#">Actualizar</a>
								 <li><a href="#">Consultar</a>
							</ul>
						</li>
						<li class="menuglosario"><a href="#">Glosario</a>
							<ul>
								 <li><a href="#">Crear</a>
								 <li><a href="#">Actualizar</a>
								 <li><a href="#">Consultar</a>
							</ul>
						</li>
						<li class="menuobligacion"><a href="#">Obligacion</a>
							<ul>
								 <li><a href="#">Crear</a>
								 <li><a href="#">Actualizar</a>
								 <li><a href="#">Consultar</a>
							</ul>
						</li>
						<li class="menuptatencion"><a href="#">Punto de Atencion</a>
							<ul>
								 <li><a href="#">Crear</a>
								 <li><a href="#">Actualizar</a>
								 <li><a href="#">Consultar</a>
							</ul>
						</li>
						<li class="menutipoperfil"><a href="#">Tipo Perfil</a>
							<ul>
								 <li><a href="#">Crear</a>
								 <li><a href="#">Actualizar</a>
								 <li><a href="#">Consultar</a>
							</ul>
						</li>
						<li class="menutipousuario"><a href="#">Tipo de Usuario</a>
							<ul>
								 <li><a href="#">Crear</a>
								 <li><a href="#">Actualizar</a>
								 <li><a href="#">Consultar</a>
							</ul>
						</li>
						<li class="usuario"><a href="#">usuario</a>
							<ul>
								 <li><a href="#">Crear</a>
								 <li><a href="#">Actualizar</a>
								 <li><a href="#">Consultar</a>
							</ul>
						</li>
						<li><a href="#">login</a></li>
						<li><a href="#">logout</a></li>
					<ul>
			  </nav>
		</header>
		<main class="logo">
			<h1><img  src="{{ base_url()}}/img/logo.png" alt=""></h1>
  	</main>
	</body>
</html>
